# Generated by Django 5.2.3 on 2025-06-12 08:48

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlink",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
